"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](dark_blue)\
$os\
$username\
[](bg:blue_gray fg:dark_blue)\
$directory\
[](bg:blue_soft_gray fg:blue_gray)\
$git_branch\
$git_status\
[](fg:blue_soft_gray bg:black)\
$c\
$rust\
$golang\
$nodejs\
$bun\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:black bg:sapphire)\
$conda\
[](fg:sapphire bg:lavender)\
$time\
[ ](fg:lavender)\
$cmd_duration\
$line_break\
$character"""

palette = 'yiyi'

[os]
disabled = false
style = "bg:dark_blue bold fg:white"

[os.symbols]
NixOS = "󱄅"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
AOSC = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:dark_blue fg:white"
style_root = "bg:dark_blue bold fg:white"
format = '[ $user]($style)'

[directory]
style = "bg:blue_gray bold fg:crust"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = " "
style = "bold fg:crust bg:blue_soft_gray"
format = '[ $symbol$branch ]($style)'

[git_status]
style = "fg:crust bg:blue_soft_gray"
format = '[($all_status$ahead_behind )]($style)'

[nodejs]
symbol = ""
style = "bg:black"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[bun]
symbol = ""
style = "bg:black"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[c]
symbol = " "
style = "bg:black"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[rust]
symbol = ""
style = "bg:black"
format = '[[ $symbol( $version) ](fg:white bg:black)]($style)'

[golang]
symbol = ""
style = "bg:black"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[php]
symbol = ""
style = "bg:black"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[java]
symbol = " "
style = "bg:black"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[kotlin]
symbol = ""
style = "bg:black"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[haskell]
symbol = ""
style = "bg:black"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[python]
symbol = ""
style = "bg:black"
format = '[[ $symbol( $version)(\(#$virtualenv\)) ](fg:crust bg:green)]($style)'

[docker_context]
symbol = ""
style = "bg:black"
format = '[[ $symbol( $context) ](fg:crust bg:sapphire)]($style)'

[conda]
symbol = "  "
style = "fg:crust bg:black"
format = '[$symbol$environment ]($style)'
ignore_base = false

[time]
disabled = false
time_format = "%R"
style = "bg:lavender"
format = '[[  $time ](fg:crust bg:lavender)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[❯](bold fg:green)'
error_symbol = '[❯](bold fg:red)'
vimcmd_symbol = '[❮](bold fg:green)'
vimcmd_replace_one_symbol = '[❮](bold fg:lavender)'
vimcmd_replace_symbol = '[❮](bold fg:lavender)'
vimcmd_visual_symbol = '[❮](bold fg:yellow)'

[cmd_duration]
show_milliseconds = true
format = " in $duration "
style = "bg:lavender"
disabled = false
show_notifications = true
min_time_to_notify = 45000

[palettes.yiyi]
dark_blue = "#0F2027"
blue_gray = "#868b90"
blue_soft_gray = "#aabbc5"
black = "#262626"
orange = "#f9753a"
rosewater = "#d8edf0"
flamingo = "#c7e6eb"
pink = "#acd8e7"
mauve = "#92cae4"
maroon = "#118998"
peach = "#149aa4"
yellow = "#1dba9e"
green = "#26c496"
teal = "#35b7b5"
sky = "#3fb1c2"
sapphire = "#44aace"
blue = "#5bb6d8"
lavender = "#78c2e2"
text = "#d6e3f2"
subtext1 = "#b8cadf"
subtext0 = "#9db3c7"
overlay2 = "#7e94ab"
overlay1 = "#647a92"
overlay0 = "#4d6078"
surface2 = "#36485f"
surface1 = "#25384e"
surface0 = "#162638"
base = "#0b1728"
mantle = "#07111f"
crust = "#040d1a"
